#!/usr/bin/env python3
"""Post or update PR comments with benchmark results."""

import argparse
import os
import sys

from github import Auth, Github


def get_github_client(token: str | None = None) -> Github:
    """Create and return a GitHub client.

    Args:
        token: GitHub token (if None, uses GITHUB_TOKEN env var)

    Returns:
        Github client instance

    Raises:
        ValueError: If no token provided
    """
    if token is None:
        token = os.environ.get("GITHUB_TOKEN")

    if not token:
        raise ValueError("GitHub token required (GITHUB_TOKEN env var or --token argument)")

    auth = Auth.Token(token)
    return Github(auth=auth)


def find_existing_bot_comment(
    github_client: Github, pr_number: int, repo: str, bot_signature: str = "*Generated by bench-bot*"
) -> int | None:
    """Find existing benchmark bot comment on a PR.

    Args:
        github_client: GitHub client instance
        pr_number: PR number
        repo: Repository name (org/repo format)
        bot_signature: Signature to identify bot comments

    Returns:
        Comment ID if found, None otherwise
    """
    try:
        repo_obj = github_client.get_repo(repo)
        pr = repo_obj.get_pull(pr_number)

        # Check issue comments (PR comments use the issues API)
        comments = pr.get_issue_comments()

        for comment in comments:
            if bot_signature in comment.body:
                return comment.id

        return None

    except Exception as e:
        print(f"Warning: Could not search for existing comments: {e}", file=sys.stderr)
        return None


def post_or_update_comment(github_client: Github, pr_number: int, repo: str, body: str, update_existing: bool = True) -> bool:
    """Post new comment or update existing benchmark bot comment.

    Args:
        github_client: GitHub client instance
        pr_number: PR number
        repo: Repository name (org/repo format)
        body: Comment body (markdown)
        update_existing: If True, update existing comment instead of creating new one

    Returns:
        True if successful, False otherwise
    """
    try:
        repo_obj = github_client.get_repo(repo)
        pr = repo_obj.get_pull(pr_number)

        if update_existing:
            # Try to find existing comment
            existing_id = find_existing_bot_comment(github_client, pr_number, repo)

            if existing_id:
                # Update existing comment
                print(f"Updating existing comment ID {existing_id}...")
                comment = pr.get_issue_comment(existing_id)
                comment.edit(body)
                print(f"✓ Updated comment on PR #{pr_number}")
                print(f"  View at: {comment.html_url}")
                return True

        # Create new comment
        print(f"Creating new comment on PR #{pr_number}...")
        comment = pr.create_issue_comment(body)
        print(f"✓ Posted comment on PR #{pr_number}")
        print(f"  View at: {comment.html_url}")
        return True

    except Exception as e:
        print(f"ERROR: Failed to post comment: {e}", file=sys.stderr)
        return False


def main() -> None:
    parser = argparse.ArgumentParser(description="Post or update PR comment with benchmark results")
    parser.add_argument(
        "pr_number",
        type=int,
        help="PR number to comment on",
    )
    parser.add_argument(
        "--repo",
        type=str,
        required=True,
        help="Repository name (org/repo format, e.g., lance-format/lance)",
    )
    parser.add_argument(
        "--body",
        type=str,
        default=None,
        help="Comment body text (markdown)",
    )
    parser.add_argument(
        "--body-file",
        type=str,
        default=None,
        help="File containing comment body text",
    )
    parser.add_argument(
        "--token",
        type=str,
        default=None,
        help="GitHub token (default: GITHUB_TOKEN env var)",
    )
    parser.add_argument(
        "--no-update",
        action="store_true",
        help="Always create new comment, never update existing",
    )

    args = parser.parse_args()

    # Get comment body
    if args.body and args.body_file:
        print("ERROR: Cannot specify both --body and --body-file", file=sys.stderr)
        sys.exit(1)

    if args.body:
        body = args.body
    elif args.body_file:
        try:
            with open(args.body_file) as f:
                body = f.read()
        except Exception as e:
            print(f"ERROR: Failed to read body file: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        # Read from stdin
        print("Reading comment body from stdin...")
        body = sys.stdin.read()

    if not body.strip():
        print("ERROR: Comment body is empty", file=sys.stderr)
        sys.exit(1)

    # Create GitHub client
    try:
        github_client = get_github_client(args.token)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    # Post or update comment
    success = post_or_update_comment(github_client, args.pr_number, args.repo, body, update_existing=not args.no_update)

    if not success:
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
